"use strict";
(() => {
  const FILES="abcdefgh", START="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1";
  const clone=o=>JSON.parse(JSON.stringify(o));
  function parseFen(fen){const [pp,turn='w',cast='-',ep='-',half='0',full='1']=fen.split(/\s+/);const b={};let r=8;for(const row of pp.split('/')){let f=0;for(const c of row){if(/\d/.test(c))f+=+c;else b[FILES[f++]+r]=c;}r--;}return{b,turn,cast,ep,half:+half,full:+full};}
  function placement(s){let out=[];for(let r=8;r>=1;r--){let row='',n=0;for(const f of FILES){const p=s.b[f+r];if(!p)n++;else{if(n){row+=n;n=0;}row+=p;}}if(n)row+=n;out.push(row);}return out.join('/');}
  function fen(s){return `${placement(s)} ${s.turn} ${s.cast||'-'} ${s.ep||'-'} ${s.half} ${s.full}`;}
  const color=p=>p===p.toUpperCase()?'w':'b', type=p=>p.toLowerCase(), opp=c=>c==='w'?'b':'w';
  const sq=(f,r)=>f>=0&&f<8&&r>=1&&r<=8?FILES[f]+r:null;
  function attacked(s,target,by){for(const [from,p] of Object.entries(s.b)){if(color(p)!==by)continue;const ff=FILES.indexOf(from[0]),fr=+from[1],tf=FILES.indexOf(target[0]),tr=+target[1],df=tf-ff,dr=tr-fr,t=type(p);if(t==='p'&&dr===(by==='w'?1:-1)&&Math.abs(df)===1)return true;if(t==='n'&&[[1,2],[2,1]].some(([a,b])=>Math.abs(df)===a&&Math.abs(dr)===b))return true;if(t==='k'&&Math.max(Math.abs(df),Math.abs(dr))===1)return true;if('brq'.includes(t)){const diag=Math.abs(df)===Math.abs(dr),line=df===0||dr===0;if((t==='b'&&!diag)||(t==='r'&&!line)||(t==='q'&&!diag&&!line))continue;const sf=Math.sign(df),sr=Math.sign(dr);let f=ff+sf,r=fr+sr,clear=true;while(f!==tf||r!==tr){if(s.b[sq(f,r)]){clear=false;break;}f+=sf;r+=sr;}if(clear)return true;}}
    return false;
  }
  function inCheck(s,c){const k=Object.keys(s.b).find(x=>s.b[x]===(c==='w'?'K':'k'));return !k||attacked(s,k,opp(c));}
  function pseudo(s){const out=[];for(const [from,p] of Object.entries(s.b)){if(color(p)!==s.turn)continue;const f=FILES.indexOf(from[0]),r=+from[1],t=type(p),c=s.turn;const add=(to,promo=null,flags='')=>{if(!to)return;const q=s.b[to];if(q&&color(q)===c)return;out.push({from,to,promotion:promo,flags,captured:q||null,piece:t});};if(t==='p'){const d=c==='w'?1:-1,start=c==='w'?2:7,last=c==='w'?8:1,one=sq(f,r+d);if(one&&!s.b[one]){if(r+d===last)for(const pr of 'qrbn')add(one,pr,'p');else add(one);const two=sq(f,r+2*d);if(r===start&&!s.b[two])add(two,null,'b');}for(const df of [-1,1]){const to=sq(f+df,r+d);if(!to)continue;if((s.b[to]&&color(s.b[to])!==c)||to===s.ep){if(r+d===last)for(const pr of 'qrbn')add(to,pr,to===s.ep?'ep':'p');else add(to,null,to===s.ep?'ep':'');}}}
      else if(t==='n'){for(const [df,dr] of [[1,2],[2,1],[-1,2],[-2,1],[1,-2],[2,-1],[-1,-2],[-2,-1]])add(sq(f+df,r+dr));}
      else if('brq'.includes(t)){const dirs=t==='b'?[[1,1],[1,-1],[-1,1],[-1,-1]]:t==='r'?[[1,0],[-1,0],[0,1],[0,-1]]:[[1,1],[1,-1],[-1,1],[-1,-1],[1,0],[-1,0],[0,1],[0,-1]];for(const [df,dr] of dirs){let nf=f+df,nr=r+dr;while(sq(nf,nr)){const to=sq(nf,nr),q=s.b[to];if(!q)add(to);else{if(color(q)!==c)add(to);break;}nf+=df;nr+=dr;}}}
      else if(t==='k'){for(let df=-1;df<=1;df++)for(let dr=-1;dr<=1;dr++)if(df||dr)add(sq(f+df,r+dr));const rank=c==='w'?1:8;if(from===`e${rank}`&&!inCheck(s,c)){if(s.cast.includes(c==='w'?'K':'k')&&!s.b[`f${rank}`]&&!s.b[`g${rank}`]&&!attacked(s,`f${rank}`,opp(c))&&!attacked(s,`g${rank}`,opp(c)))add(`g${rank}`,null,'k');if(s.cast.includes(c==='w'?'Q':'q')&&!s.b[`d${rank}`]&&!s.b[`c${rank}`]&&!s.b[`b${rank}`]&&!attacked(s,`d${rank}`,opp(c))&&!attacked(s,`c${rank}`,opp(c)))add(`c${rank}`,null,'q');}}
    }return out;
  }
  function apply(s,m){const n=clone(s),p=n.b[m.from],c=color(p),t=type(p);delete n.b[m.from];if(m.flags.includes('ep'))delete n.b[m.to[0]+(+m.to[1]+(c==='w'?-1:1))];n.b[m.to]=m.promotion?(c==='w'?m.promotion.toUpperCase():m.promotion):p;if(m.flags.includes('k')){const r=c==='w'?1:8;n.b[`f${r}`]=n.b[`h${r}`];delete n.b[`h${r}`];}if(m.flags.includes('q')){const r=c==='w'?1:8;n.b[`d${r}`]=n.b[`a${r}`];delete n.b[`a${r}`];}let cast=n.cast;if(t==='k')cast=cast.replace(c==='w'?/[KQ]/g:/[kq]/g,'');if(m.from==='a1'||m.to==='a1')cast=cast.replace('Q','');if(m.from==='h1'||m.to==='h1')cast=cast.replace('K','');if(m.from==='a8'||m.to==='a8')cast=cast.replace('q','');if(m.from==='h8'||m.to==='h8')cast=cast.replace('k','');n.cast=cast||'-';n.ep=m.flags.includes('b')?m.from[0]+((+m.from[1] + +m.to[1])/2):'-';n.half=(t==='p'||m.captured||m.flags.includes('ep'))?0:n.half+1;if(c==='b')n.full++;n.turn=opp(c);return n;}
  function legal(s){return pseudo(s).filter(m=>!inCheck(apply(s,m),s.turn));}
  function san(s,m){if(m.flags.includes('k'))return 'O-O'+suffix(s,m);if(m.flags.includes('q'))return 'O-O-O'+suffix(s,m);const p=s.b[m.from],t=type(p),capture=!!(m.captured||m.flags.includes('ep'));let x='';if(t!=='p'){x=t.toUpperCase();const peers=legal(s).filter(z=>z.to===m.to&&z.from!==m.from&&z.piece===t);if(peers.length){const sameFile=peers.some(z=>z.from[0]===m.from[0]),sameRank=peers.some(z=>z.from[1]===m.from[1]);x+=!sameFile?m.from[0]:!sameRank?m.from[1]:m.from;}}else if(capture)x=m.from[0];x+=(capture?'x':'')+m.to;if(m.promotion)x+='='+m.promotion.toUpperCase();return x+suffix(s,m);}
  function suffix(s,m){const n=apply(s,m);if(!inCheck(n,n.turn))return '';return legal(n).length?'#'.replace('#','+'): '#';}
  function matchTransition(fromState,toPlacement){const hits=legal(fromState).filter(m=>placement(apply(fromState,m))===toPlacement);if(hits.length!==1)return null;const m=hits[0];return{move:{...m,san:san(fromState,m),uci:m.from+m.to+(m.promotion||'')},state:apply(fromState,m)};}
  function moveSan(s,text){const norm=String(text).replace(/[!?+#]+$/g,'').replace(/0/g,'O');return legal(s).find(m=>san(s,m).replace(/[+#]$/,'')===norm)||null;}
  window.CRBChess={START,parseFen,fen,placement,legal,apply,san,matchTransition,moveSan};
})();
